name: CI

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: true
          version: 8.5.1

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
      
      - name: Test
        run: pnpm run test
